services:
  goofy_fis_be:
    container_name: goofy_fis_be
    build:
      context: .
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      CERT_DOMAIN: "your.domain.com"
      KEYSTORE_PASSWORD: "change-me-to-a-strong-password"
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
      - "./fis_data:/srv/data"
    restart: always