# Main Spring Settings
spring.application.name=goofy-protocol-fis-be
spring.output.ansi.enabled=always
spring.config.import=optional:file:.env[.properties]

# Main Server Settings
server.port=8080
spring.web.error.include-message=always
spring.devtools.add-properties=true

# General Data
goofy.general.frontend-url=http://localhost:3000
goofy.general.url=http://localhost:8080
goofy.general.name=Goofy FIS Reference Implementation (Dev)
goofy.general.description=Goofy FIS Reference Implementation for the Goofy Protocol
goofy.general.contact=Contact: real@mail.com
goofy.general.version=0.7.1-dev
goofy.general.keypair.type=EC_C25519

# Storage
goofy.storage.use-temp-dir=false
goofy.storage.create-directories=true
goofy.storage.base-user-databases-path=user_data/databases
goofy.storage.base-user-buckets-path=user_data/buckets

# Registration
goofy.register.registrations-allowed=true
goofy.register.check-method=manual

# Max Data sizes
goofy.auth.max-request-bytes=150000000
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=150MB

# Main H2 DB
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:./fis_dev.db;AUTO_SERVER=true
spring.datasource.username=sa
spring.datasource.password=sa

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true


# Quotas
## Base User Quotas (General)
goofy.quota.base.general.max-name-size=100

## Base User Quotas (Identity Entries)
goofy.quota.base.identity.max-entries=10
goofy.quota.base.identity.max-service-entries=5

## Base User Quotas (Table Access)
goofy.quota.base.table.max-db-size=5000000
goofy.quota.base.table.max-field-size=100000
goofy.quota.base.table.max-tables=10
goofy.quota.base.table.max-cols=100
goofy.quota.base.table.max-rows=1000000
goofy.quota.base.table.max-permission-count=100
goofy.quota.base.table.max-lock-duration-seconds=60
goofy.quota.base.table-query.max-query-length=100000
goofy.quota.base.table-query.max-condition-count=40
goofy.quota.base.table-query.max-result-count=100

## Base User Quotas (Bucket Access)
goofy.quota.base.bucket.max-bucket-size=100000000
goofy.quota.base.bucket.max-item-size=50000000
goofy.quota.base.bucket.max-item-count=1000000
goofy.quota.base.bucket.max-permission-count=100

# Admin Quotas
## Admin User Quotas (General)
goofy.quota.admin.general.max-name-size=100

## Admin User Quotas (Identity Entries)
goofy.quota.admin.identity.max-entries=10
goofy.quota.admin.identity.max-service-entries=10

## Admin User Quotas (Table Access)
goofy.quota.admin.table.max-db-size=25000000
goofy.quota.admin.table.max-field-size=100000
goofy.quota.admin.table.max-tables=20
goofy.quota.admin.table.max-cols=100
goofy.quota.admin.table.max-rows=5000000
goofy.quota.admin.table.max-permission-count=200
goofy.quota.admin.table.max-lock-duration-seconds=60
goofy.quota.admin.table-query.max-query-length=200000
goofy.quota.admin.table-query.max-condition-count=50
goofy.quota.admin.table-query.max-result-count=500

## Admin User Quotas (Bucket Access)
goofy.quota.admin.bucket.max-bucket-size=10000000000
goofy.quota.admin.bucket.max-item-size=100000000
goofy.quota.admin.bucket.max-item-count=1000000
goofy.quota.admin.bucket.max-permission-count=200