# THIS IS JUST AN EXAMPLE OF A PROD CONFIG, WILL PROBABLY CHANGE
# Main Spring Settings
spring.application.name=goofy-protocol-fis-be
spring.output.ansi.enabled=always
spring.config.import=optional:file:.env[.properties]

# Main Server Settings
server.port=8080
spring.web.error.include-message=never

# General Data
goofy.general.frontend-url=https://fe.fis.rocc.systems
goofy.general.url=https://fis.rocc.systems
goofy.general.name=Goofy FIS Reference Implementation
goofy.general.description=Goofy FIS Reference Implementation for the Goofy Protocol
goofy.general.contact=Contact: real@mail.com
goofy.general.version=0.0.1

# Registration
goofy.register.registrations-allowed=true
goofy.register.check-method=manual

# Max Data sizes
goofy.auth.max-cache-bytes=60000000
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=60MB

# Main H2 DB
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
spring.datasource.url=jdbc:h2:./fis_main.db;AUTO_SERVER=true
spring.datasource.username=sa
spring.datasource.password=sa

