# Main Spring Settings
spring.application.name=goofy-protocol-fis-be
spring.output.ansi.enabled=always
spring.config.import=optional:file:.env[.properties]

# Main Server Settings
server.port=8080
spring.web.error.include-message=always
spring.devtools.add-properties=true

# General Data
goofy.general.frontend-url=http://localhost:1234
goofy.general.url=http://localhost:8080
goofy.general.name=Goofy FIS Reference Implementation (Dev)
goofy.general.description=Goofy FIS Reference Implementation for the Goofy Protocol
goofy.general.contact=Contact: real@mail.com
goofy.general.version=0.0.1-dev
goofy.general.keypair.type=EC_C25519

# Registration
goofy.register.registrations-allowed=true
goofy.register.check-method=manual

# Max Data sizes
goofy.auth.max-cache-bytes=60000000
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=60MB

# Main H2 DB
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:./fis_dev.db;AUTO_SERVER=true
spring.datasource.username=sa
spring.datasource.password=sa

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true